### ISSUE TITLE
Investigate adding dynamic simulation alongside asoredit

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#32]
https://community.bistudio.com/wiki/Arma_3_Dynamic_Simulation

**Comment by suitsy** [comment]
enableDynamicSimulationSystem bool

Toggles the Dynamic Simulation system.
dynamicSimulationSystemEnabled

Returns true if the Dynamic Simulation system is active, otherwise returns false.
object/group enableDynamicSimulation bool

Adds/Removes object or group to/from Dynamic Simulation system.
dynamicSimulationEnabled object/group

Returns true if group or object has Dynamic Simulation, otherwise returns false.
activationCategory setDynamicSimulationDistance distance

Sets activation distance for given activation category. The recognized activation categories are "Group", "Vehicle", "EmptyVehicle" and "Prop".
dynamicSimulationDistance activationCategory

Returns what activation distance is set for given activation category. The recognized activation categories are "Group", "Vehicle", "EmptyVehicle" and "Prop".
activationMultiplier setDynamicSimulationDistanceCoef multiplier

Sets the specific activation distance multiplier value. Currently the only recognized activation multiplier is "IsMoving".
dynamicSimulationDistanceCoef activationMultiplier

Returns value of the given activation distance multiplier. Currently the only recognized activation multiplier is "IsMoving".
unit triggerDynamicSimulation bool

Controls ability of given unit to activate dynamically disabled entities. If false, dynamically disabled entities won't be activated by units presence.
canTriggerDynamicSimulation unit

Returns true if given unit can activate dynamically disabled entities, otherwise return false.

**Comment by suitsy** [comment]
Not Required
