### ISSUE TITLE
Make VS and GS Objects with 3DEN menu for params

### ISSUE THREAD

**Issue by suitsy** [LecksC/ASOR_Bugs#35]
Make stands or other objects with a 3den menu to enable it as a ASORGS or ASORVS and have options to enable features

ie: ASORGS
Blacklist Options

ie: ASORVS
Available Vehicle Types, Tanks, Boats, Cars etc

**Comment by LecksC** [comment]
Not sure what blacklist options could be suitable for the gear selector. It's all been set up in configs, so the 3den module would have to somehow look at the configs to work out what options to show you (adversarial, default, etc).

The vehicle selector menu should be easy enough, but the hard part with that will be linking it to something for spawn points consistently. Ideal solution would be syncing the sign to open them to custom heli/vehicle pads. Each pad would have to have some kind of ID or Name + Order.

Both also build their databases during preinit because it's much faster. The issue here is the 'Enabled' flag needs to be available during preinit, which is well before modules load. Would have to either make it so it builds the database every time (even for missions that don't use the gear selector, slowing down their loading at least), or make it so the databases only start loading after the module, which may cause delays when people go to get their gear (like VAS used to do).

Maybe there's some way to add a custom mission setting in where you choose respawn templates and other stuff that used to be in description.ext?

**Comment by suitsy** [comment]
yeah sorry not sure what I was thinking in regards to the 'blacklist options'. for the GS its really just making place-able objects that are gear selectors hey.

for the VS if we made custom ground textures like helipads say "asor_pad_1" could you do the sort and name order based on the classname?

Not sure I follow on the database stuff there, thanks the blacklist yeah? Probably not required. Would be cool if you could enable a certain blacklist in a lobby server setting though I guess. Could have black kit available for example by turning BlackOps gear selector option on?

**Comment by suitsy** [comment]
I already have one GS place-able create, just need to add some diff types i reckon and gtg on that bit.

**Comment by MitchDrage** [comment]
I'm working on creating Placeable pads for VS.
Also going to make open VS a self-interact option when in proximity to the pad.

**Comment by LecksC** [comment]
I think a sign is better (more obvious) than a self interact?

Keep in mind that the VS needs to work with planes, helicopters, vehicles and boats, all of which will have different 'pad types' (hangar area/dock/helipad/parking bay). It would be difficult to make a visual representation for hangar/docks types, so maybe they could be a module instead.

Best solution I can think of would be to have 4 placeable pads per type (mainly so they can be visually numbered 1234) with 3den attributes to choose vehicle types and any other VS options, and a placeable sign that you can synchronize any number of the pads to which will show vehicle selector options for each.

**Comment by suitsy** [comment]
the benefit we would get from the proxy self interact though is zues placeable vehicle selectors, if everyone knows thats how it works and we have the pads on the ground, they will know to go upto it and self interact anyway?

**Comment by suitsy** [comment]
@LecksC completed this and its functioning perfectly.
