### ISSUE TITLE
ASOR Tablet

### ISSUE THREAD

**Issue by Heilidhe** [LecksC/ASOR_Bugs#61]
Forget FTX Modules.

## FTX Tablet
Strictly Theoretical and an IDEA - Not even sure if 100% possible.

- Thinking of Making (or trying) a Tablet bit like the 506th IR's CTab.

1) Main reason is making FTX dialogues and course activation be readable in this tablet (so people wanting to do training and perhaps porting the FTX can change the Information in Dialogues and Activation of courses, in a module, rather than in the mission file. (Also stops dialogues from getting annoying - as they're currently trigger activated - allowing people to choose to read might be better).

## Extension

2) Secondly, could remove all Mission related Objectives in the Map Tabs (and the INFO on ASOR like the WIki) and pass the information into the Tablet. 
- Encourages briefings in GAME rather than the map tabs, which was something suits mentioned awhile ago - not sure if still desired.
Allow tablet to have a viewable map. Would simply be for immersion and better looking than the map tabs.
Could also add UAV Feeds for SQL's and CMD when there are Active UAV's in the sky.

3) Could even do a personal message system, which would remove need for people to ALT-Tab to discord to contact people in an Emergency. 

Majority of these ideas, might be pretty superfluous, but for the FTX, I'm feeling that its solid.

Its functionality wouldn't really be as an on screen tactical tablet - there's already 100 of them - but rather just passing information and displaying it nicely for both the FTX and perhaps Missions.

**Comment by Woodsylord** [comment]
Something like this may be useful with Instants Intelligence functions.

**Comment by suitsy** [comment]
Idea: Could tie into this. Is to have either a laptop or tablet that undercover teams use to send sitreps and intel. Real deep cover teams send burst transmissions, hard to pin point and triangulate and generally operate in the noise range without going into to much detail. It would be cool to implement some kind of SMS setup where teams can update intel or send sitreps rather than have to carry a LR radio which is clearly visible.

**Comment by Woodsylord** [comment]
If we can get SMS functioning, would be useful having a picture or video function. Could use something similar to the PIP from the UAV, with the camera as the UAV Camera and the recipient getting the pic or video? That way covert teams could sent data back to strike elements.

**Comment by Heilidhe** [comment]
Yeah in game SMS/PM was something i wanted to do, although I stopped anything related to Intel and outside of the FTX because Instant was working on his Hacking Computer stuff. Might have to hit him up, regarding it.

**Comment by Woodsylord** [comment]
Having the back end "OS" the same across a laptop, phone and tablet... could that be easier?

**Comment by Heilidhe** [comment]
Perhaps. We could use muffins template of UI Dialogs which he already has for the laptops, but it would need to be edited to fit/customize to a Mobile Phone screen background.

I reckon we use what Muffin has already, and expand on it, if he's willing - think he is busy with uni and stuff rn.

**Comment by Instant-Muffin** [comment]
In theory it's already possible to have it the same across different objects. Last time I worked on it, it could be given a list of "programs" and code that would be run with each and they would appear on the menu when you open it and could be clicked to run. I was trying to get the email interface to open properly. Have thought since though that it might be better to be a list of local documents or something rather than email. The interface works by literally spawning the object and drawing the dialog over it. So all that would need doing is changing the object and the dimensions. Sending pictures or messages could be a "program" pretty easily too. Depends on whether a solution we make is better than the ones that already exist.

It also needs to be made an actual mod instead of a mission. Something I haven't done yet. The code shouldn't really need changing it's just easier to edit as a mission cause I don't need to restart the game every two minutes.

**Comment by Heilidhe** [comment]
Too hard, too pointless.
